development:
  clients: &development_clients
    default:
      database: development
      hosts:
        - localhost:27017
  sessions:
    <<: *development_clients

test:
  clients: &test_clients
    default:
      database: test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - localhost:27017
  sessions:
    <<: *test_clients
