development:
  clients: &development_clients
    default:
      database: sard_development
      hosts:
        - localhost:27017
  sessions:
    <<: *development_clients

test:
  clients: &test_clients
    default:
      database: sard_test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - localhost:27017
  sessions:
    <<: *test_clients
